@startuml
'https://plantuml.com/class-diagram

class utilizatorul
class browser
class landingpage
class zona_numele_aplicatiei
class zona_prezentare
class zona_descriere
class fereastra_cookie
class chenar_functionalitati_prezentare

class menu
class categorie_menu
class mini_menu

class caseta_search
class buton_login
class buton_quickbuild

class fereastra_login
class caseta_username
class caseta_password
class buton_login_cont

landingpage "1" *--- "1..*" chenar_functionalitati_prezentare
landingpage .up. fereastra_cookie
landingpage "1" *-down- "1" zona_numele_aplicatiei
landingpage "1" *-down- "1" zona_prezentare
landingpage "1" *-down- "1" zona_descriere
landingpage "1" *-left- "1" menu
landingpage "1" *--- "1" caseta_search
landingpage "1" *-- "1" buton_quickbuild
landingpage "1" *-- "1" buton_login

menu "1" *-- "1" buton_menu

menu "1" *-- "1..*" categorie_menu
categorie_menu "1" *-- "1..*" mini_menu

fereastra_login -- caseta_password
fereastra_login -- caseta_username
fereastra_login -- buton_login_cont


class landingpage
{
zona_numele_aplicatiei
zona_prezentare
zona_descriere
}

class zona_numele_aplicatiei
{
length
height
brand_picture
}

class zona_prezentare
{
length
height
text
}

class zona_descriere
{
length
height
text
}

class fereastra_cookie
{
length
height
text
buton_accept
buton_refuse
setcookies()
notsetcookies()
}

class buton_menu
{
length
height
label
status
expand_when_clicked()
close_when_click_elsewhere()
}

class categorie_menu
{
length
width
label
expand_when_hover()
}

class mini_menu
{
label_mini_menu
picture
}

class menu
{
length
height
symbol
expand_when_clicked()
}

class caseta_search
{
status
length
height
text
search_symbol
accept_input()
search_in_app()
afisare_fereastra_rezultate()
}

class chenar_functionalitati_prezentare
{
picture
label
}

class buton_login
{
length
height
picture
afiseaza_fereastra_login()
}

class caseta_username
{
length
height
label
accept_input()
check_username()
}

class caseta_password
{
length
height
label
accept_input()
check_password()
}

class buton_login_cont
{
length
height
text
set_app_logedin()
}

class buton_quickbuild
{
length
height
label

}
@enduml