@startuml
'https://plantuml.com/use-case-diagram

:Utilizator: as user

user ---> (afiseazaLanding Page) : Introduce URL pentru prima data

(afiseazaLanding Page) ---> (AcceptCookies) : accepta sau respinge cookies


user --> (afiseaza meniul va glisa in jos) : Click pe menu

user --> (afiseaza subcategorie meniu) : hovermouse pe item din listaMenu

user --> (se activeaza caseta search)

user --> (app verifica formatul sirului de caractere care trebuie sa aiba urmatorul format xxxxxxxx@gmail.com) : tasteaza in casuta de email





@enduml