@startuml
'https://plantuml.com/use-case-diagram

:Utilizator: as user

user ---> (AcceptCookies) : Introduce URL
(AcceptCookies) ----> (Landing Page) : Accepta Cookies

user --> (menu) : Click pe menu
(menu) --> (subcategoriemenu) : hovermouse pe item din listaMenu





@enduml